version: '3.8'

networks:
  nginx_net:
    driver: bridge

services:

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net

  webcolorblue:
    image: fabricioveronez/web-color:blue
    # ports:
    #   - 8081:80
    networks:
      - nginx_net

  webcolorgreen:
    image: fabricioveronez/web-color:green
    # ports:
    #   - 8082:80
    networks:
      - nginx_net

  conversaotemperatura01:
    image: fabricioveronez/conversao-temperatura:v1
    # ports:
    #   - 8083:8080
    networks:
      - nginx_net
  conversaotemperatura02:
    image: fabricioveronez/conversao-temperatura:v1
    # ports:
    #   - 8084:8080
    networks:
      - nginx_net
  conversaotemperatura03:
    image: fabricioveronez/conversao-temperatura:v1
    # ports:
    #   - 8085:8080
    networks:
      - nginx_net